lane :test do
  amazon_app_submission(
    client_id: "<CLIENT_ID>",
    client_secret: "<CLIENT_SECRET>",
    app_id: "<APP_ID>",
    # Optional
    apk_path: "<APK_PATH>",
    upload_apk: true,
    changelogs_path: "<CHANGELOG_PATH>",
    upload_changelogs: false,
    submit_for_review: false,
  )
end